(setq user-full-name "Dmitry Pribysh")
(setq user-mail-address "dmand@yandex.ru")
(add-to-list 'load-path  "~/.emacs.d/")

(require 'my-packages)
(require 'my-linum-stuff)
(require 'my-buffers)
(require 'my-org-stuff)
(require 'my-color-theme)
(require 'my-speedbar-stuff)
(require 'my-auto-complete-stuff)
(require 'my-yasnippet-stuff)
(require 'my-python-stuff)
(require 'my-scala-stuff)
(require 'my-flymake-stuff)
(require 'my-key-bindings)
(require 'my-calendar-stuff)
(require 'my-auto-modes)
(require 'my-global-emacs-stuff)
(require 'my-zone-stuff)

;; device-specific overrides (e.g. no `zoning` on chromebook) go here
(require 'my-overrides)
