#!/bin/bash

if [ "$1" = "" ]; then
  echo "Error: first argument should be image to write"
  fail=1
fi
if [ "$2" = "" ]; then
  echo "Warning: you didn't specify device to write image to. I will assume that this is /dev/sdb"
  disk="/dev/sdb"
else
  disk="$2"
fi
if [ "$fail" = "1" ]; then
  exit 1
fi


if [ "$2" = "/dev/sda" ]; then
  echo "I won't let you write on /dev/sda"
  echo "Also, you owe me a beer for that."
  exit 1
fi

image="$1"

dd bs=1M if="$image" of="$disk" && sync && beep && sync && beep
